server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    max-swallow-size: -1
spring:
  application:
  name: backup
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.railway.internal:3306/railway?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: WefmYCjeVwpAKzoKHhikJFXOwxOrLFMM
  jpa:
    hibernate:
      ddl-auto: update   # create ? ?? ?????? ??? ??? ??? ?? ??? ??????
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false
        highlight_sql: true
      open-in-view: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace